### ISSUE TITLE
Might be better to use something other than .f3d & .f3z file formats

### ISSUE THREAD

**Issue by justinclift** [DragonComputer/DragonArmor#2]
With the .f3d and .f3z file formats - from memory of when I used to use Fusion 360 - they're undocumented and change over time:

* https://forums.autodesk.com/t5/fusion-360-design-validate/file-format-specification-for-f3d/td-p/5804681

It might be better to use a file format like (say) STEP or IGES which are standardised and widely supported. eg can be opened by not just Fusion 360, but many other commercial and OSS packages too

Both of those generally contain rich levels of object data, and at least STEP (not sure about IGES) can contain model construction history so timeline/construction info is preserved.

**Comment by mertyildiran** [comment]
@justinclift that's a good point :+1: 

I haven't opened Fusion 360 for about 2 months so my knowledge could be rusty and forgive me (and please correct me) if I'm wrong but as far as I know it's not possible to export **distributed designs** (`.f3z`) in STEP or IGES formats.

Although we are able to publish `.f3d` files in STEP or IGES formats, they won't be functional inside [TheHelmet.f3z](https://github.com/DragonComputer/DragonArmor/blob/master/DragonHelmet/TheHelmet.f3z) file. So what's the point to having files in STEP or IGES formats inside the repository? :blush: 

Also we don't track history of any CAD model in this repository. Because it's too expensive for GitHub's policies ([What is my disk quota?](https://help.github.com/articles/what-is-my-disk-quota/)) Instead we use [Git LFS](https://git-lfs.github.com/) and don't track the history of [these files](https://github.com/DragonComputer/DragonArmor/blob/master/.gitattributes).

*P.S. I should clarify that GitHub's policies are completely fair and reasonable.*

**Comment by justinclift** [comment]
Hmmm, when you say "distributed designs" are you meaning an assembly made up of multiple objects/files?

STEP definitely can contain multiple objects.  I don't remember if it allows for calling out to other files though. :smile:

It might be a case of needing to saving the high level assembly as a STEP instead of the individual parts.

My point with .f3d/.f3z is also that since the file format changes over time (and doesn't appear to contain a version number) that files you save here now may not be usable by future versions of Fusion 360.  As lousy as that sounds. 😦

**Comment by mertyildiran** [comment]
@justinclift Distributed design = a file with `.f3z` extension. Fusion 360 does not allow me to export distributed designs other then `.f3z` format.

The files are also stored in our Autodesk cloud, so we will not lose any data. This repository's purpose is **not version control** for CAD files. The primary purpose of this repository is **publishing** the CAD files. The secondary purpose of this repository is tracking history of any data(small), plan and program files.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by mertyildiran** [comment]
@justinclift I decided that you were right. So I migrated from `.f3d` to `.stp` and `.stl` with https://github.com/DragonComputer/DragonArmor/commit/047047a404357fe47ae0af77f573f62281014cae. Could please you verify the repository's state by importing into Fusion 360? Thanks for these suggestions. :+1: :blush:

**Comment by justinclift** [comment]
Cool.  Personally I can't verify this, as I don't use Fusion 360 any more.

Someone else should probably be interested enough to try it out though. :smile:

**Comment by mertyildiran** [comment]
@justinclift OK then I'm closing this issue. Thank you so much! :blush:
